// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NpmTaskRunner
{
    static class Vsix
    {
        public const string Id = "d7f89ba3-815c-4feb-89b9-68d1654e2138";
        public const string Name = "NPM Task Runner";
        public const string Description = @"Adds support for npm scripts defined in package.json directly in Visual Studio's Task Runner Explorer";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "npm, package.json, task runner, scripts";
    }
}
