// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NpmTaskRunner
{
    internal sealed partial class Vsix
    {
        public const string Id = "c5203f5f-4785-4c09-b383-688a100a9f5d";
        public const string Name = "NPM Task Runner";
        public const string Description = @"Adds support for npm scripts defined in package.json directly in Visual Studio's Task Runner Explorer. Includes full support for Yarn";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "npm, package.json, task runner, scripts, yarn";
    }
}
